name: Deploy to Cloudflare Pages

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration=${{ github.ref_name == 'master' && 'production' || 'development' }}

      - name: Deploy to Cloudflare Pages
        if: startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/development') # Проверка на ветки master и development
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ngrx-signal-based-boxes
          directory: dist/cloudflare
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}